version: '3.1'

services:
      app:
        build:
          context: .
          dockerfile: Dockerfile
        depends_on:
          - db
       
      db:
        build: 
          context: .
          dockerfile: mysql.Dockerfile
        environment:
          - MYSQL_DATABASE=
          - MYSQL_PASSWORD=
          - MYSQL_ROOT_PASSWORD=
        volumes: 
          - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:





       

    